default: &default
  adapter: mysql2
  host: localhost
  username: <%= ENV['MYSQL_GYMPASSTV_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_GYMPASSTV_PASSWORD'] %>
  database: gympasstv_dev

development:
  <<: *default
  database: gympasstv_prod
  username: gympasstv_prod
  password: '6y39a0018'

test:
  <<: *default
  database: gympasstv_test

staging:
  <<: *default
  database: gympasstv_prod

production:
  <<: *default
  database: gympasstv_prod
  username: gympasstv_prod
  password: '6y39a0018'
